// Generated by scripts/art/finish.mjs cursors – do not edit by hand.
// Hot spot (x, y in px) of each painted cursor public/icons/cursor-<name>.png (40 px).
export const CURSOR_SIZE = 40;
export const CURSOR_HOTSPOTS = {"hand":[2,1],"chop":[1,9],"mine":[8,6],"build":[9,4],"attack":[1,1]};
