// Create buildings from the icon atlas: icon (128 px) → concept image (image model) → Meshy 7.1 (one image) →
// one GLB with levels of detail per player colour.
//
//   node scripts/asset-gen/building.mjs concept <id>   # concept from the icon (assets-src/buildings/<id>/concept.png)
//     [--model openai/gpt-5.4-image-2] [--out a]       # variant concept-a.png; pick <id> a adopts it
//   node scripts/asset-gen/building.mjs set castle,castle2,castle3 | cut castle,castle2,castle3 set-v2.png   # all levels in one image, cut out
//   node scripts/asset-gen/building.mjs winter <id>    # winter version of a tree/bush → <id>_winter/concept.png
//   node scripts/asset-gen/building.mjs model <id>     # Meshy: image → 3D (raw.glb)
//   node scripts/asset-gen/building.mjs build <id>     # → public/models/buildings/<file>_<colour>.glb (+ .lod1/.lod2)
//   node scripts/asset-gen/building.mjs all <id>
//
// assets-src/buildings/<id>/spec.json: { "icon": "b-residence", "file": "house", "polycount": 8000, "describe": "…" }
// Team colour: a pennant/banner in magenta; build recolours it per player (brightness stays). spec.banner = false: none (ruins).

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import sharp from 'sharp';
import { NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import { prune, dedup, meshopt } from '@gltf-transform/functions';
import { MeshoptDecoder, MeshoptEncoder } from 'meshoptimizer';
import { reexecWithProxy, meshy, meshyWait, download, dataUri, generateImage, spend, ROOT } from './lib.mjs';
import { rasterTriangles, fillGutters } from './texraster.mjs';
import { markerWeight } from './postprocess.mjs';
import { requireAssetsSrc } from '../require-assets-src.mjs';


const DIR = path.join(ROOT, 'assets-src/buildings');
const OUT = path.join(ROOT, 'public/models/buildings');
/** Player colours as in the game (ASSET_COLORS order). */
export const PLAYER_COLORS = { blue: 0x2f5d9e, red: 0xa8323a, green: 0x3d8a4a, yellow: 0xc08a2a };
const IMAGE_MODEL = 'bytedance-seed/seedream-5-0-flash'; // 0.02 $ per image, style via reference images (comparison in docs/MODELLE.md)

await MeshoptDecoder.ready;
await MeshoptEncoder.ready;
const io = new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({ 'meshopt.decoder': MeshoptDecoder, 'meshopt.encoder': MeshoptEncoder });

const dirOf = (id) => path.join(DIR, id);
const readSpec = (id) => JSON.parse(fs.readFileSync(path.join(dirOf(id), 'spec.json'), 'utf8'));
const jobFile = (id) => path.join(dirOf(id), 'job.json');
const loadJob = (id) => (fs.existsSync(jobFile(id)) ? JSON.parse(fs.readFileSync(jobFile(id), 'utf8')) : {});
const saveJob = (id, j) => fs.writeFileSync(jobFile(id), JSON.stringify(j, null, 2) + '\n');

/** Icon from the atlas, enlarged (reference for the image model). */
async function iconImage(name, size = 512) {
  const layout = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets-src/icons/layout.json'), 'utf8'));
  const i = layout.names.indexOf(name);
  if (i < 0) throw new Error(`Icon ${name} missing in the atlas`);
  const atlas = path.join(ROOT, 'public/icons/symbols.webp');
  const cs = (await sharp(atlas).metadata()).width / layout.cols;
  return sharp(atlas).extract({ left: (i % layout.cols) * cs, top: Math.floor(i / layout.cols) * cs, width: cs, height: cs })
    .resize(size, size, { kernel: 'lanczos3' }).flatten({ background: '#ffffff' }).png().toBuffer();
}

/** Style template for buildings: a house generated by the user in ChatGPT (game-graphics look, not clay). */
const STYLE_HOUSE = path.join(ROOT, 'assets-src/buildings/style-house.webp');

/** Prompt: image 1 = draft (icon or approved previous stage), image 2 = style template. */
/**
 * Uniform upgrade pattern (all buildings): same footprint, each level taller and more solid.
 * The game scales every model to its footprint – the height comes only from the proportions of the concept.
 */
export const LEVEL_RULES = {
  1: 'Upgrade level 1 of 3: a LOW single-storey building – the walls are only about one door high and the roof starts right above the door; the whole building is clearly wider than it is tall. Wood, clay and simple materials, modest details.',
  2: 'Upgrade level 2 of 3: SAME footprint, now TWO full storeys – two rows of windows stacked above each other below the roof, about as tall as it is wide. Stone ground floor, more details (shutters, lantern, flower box).',
  3: 'Upgrade level 3 of 3: SAME footprint, now THREE full storeys – three rows of windows stacked above each other below the roof, a narrow tall townhouse clearly taller than it is wide. Mostly stone with half-timbering, the richest details.',
};

export const CONCEPT_PROMPT = (describe, fromLevel, level) => [
  fromLevel
    ? 'Image 1 is the approved previous upgrade level of this building. Draw the NEXT upgrade level of the SAME building, same art style, colors and materials:'
    : 'Image 1 is a tiny game icon of the building: take its design (shape, layout, materials, colors) from it.',
  level ? LEVEL_RULES[level] : '',
  describe ?? '',
  'Image 2 defines ONLY the art style (ignore its yard, fence, grass and props): a polished stylized 3D asset for a PC',
  'medieval village-building strategy game, rendered like a hand-painted game model – chunky, slightly exaggerated',
  'proportions; thick wooden beams with rounded, bevelled ends and visible painted wood grain; oversized terracotta roof',
  'tiles, each with a painted highlight; cream plaster with soft stains; light grey stone blocks with bevelled edges;',
  'iron fittings; warm saturated but natural colors; crisp clean edges; soft light from the upper left with gentle',
  'shadows. Not clay, not plasticine, not a toy, not pastel, not photorealistic, no outlines.',
  'Composition: the building alone, isometric three-quarter view from above (about 35°), front door and one side visible,',
  'centered, filling about 70 % of the image, plain uniform light grey background, no ground, no base plate, no smoke,',
  'no people, no text or letters anywhere. Only ONE door on the whole building (on the front); the side walls have windows only.',
  'On the roof: ONE cloth banner on a short pole in pure magenta (#FF00FF) as team color; magenta nowhere else.',
  'No blue anywhere (blue is a player color); all roofs in terracotta tiles.',
].join(' ');

async function concept(id, opts = {}) {
  const spec = readSpec(id), dir = dirOf(id);
  // Image 1: approved previous stage (spec.from) or the icon from the atlas; image 2: style template
  let first;
  if (spec.from) first = fs.readFileSync(path.join(dirOf(spec.from), 'concept.png'));
  else { first = await iconImage(spec.icon); fs.writeFileSync(path.join(dir, 'icon.png'), first); }
  // keep references small (input image tokens cost too): the model recognises style and shape even at 512 px
  const refs = [await sharp(first).resize(512, 512, { fit: 'inside' }).png().toBuffer(), await sharp(STYLE_HOUSE).resize(768).png().toBuffer()];
  const prompt = CONCEPT_PROMPT(spec.describe, !!spec.from, spec.level);
  const imageModel = opts.model ?? spec.imageModel ?? IMAGE_MODEL;
  const { buf, cost } = await generateImage(imageModel, prompt, refs);
  const res = { usage: { cost } };
  // --out <name>: variant for comparison (concept-<name>.png), concept.png stays
  const out = path.join(dir, opts.out ? `concept-${opts.out}.png` : 'concept.png');
  if (!opts.out && fs.existsSync(out)) { let n = 1; while (fs.existsSync(path.join(dir, `concept-v${n}.png`))) n++; fs.renameSync(out, path.join(dir, `concept-v${n}.png`)); }
  fs.writeFileSync(out, buf);
  const job = loadJob(id);
  (job.concepts ??= []).push({ model: imageModel, prompt, from: spec.from ?? spec.icon, file: path.basename(out), cost: res.usage?.cost });
  if (!opts.out && job.model) { (job.oldModels ??= []).push(job.model); delete job.model; } // new concept → the old model no longer applies
  saveJob(id, job);
  console.log(out, res.usage?.cost ? `(${res.usage.cost.toFixed(3)} $, ${JSON.stringify(res.usage.completion_tokens_details ?? {})} ${res.usage.prompt_tokens}/${res.usage.completion_tokens} tokens)` : '');
}

/**
 * All upgrade levels of a building in ONE image (same construction, same scale, same footprint), then
 * cut out: concept.png per level. Templates: icon, style image, finished house (style and scale).
 * ids: folders of the levels in order; the first spec.json carries icon and describe (overall description),
 * each level its own describe.
 */
/**
 * Uniform upgrade pattern for all buildings: same footprint, one more storey per level and more valuable material.
 */
export const SET_PATTERN = 'All levels have exactly the same footprint (same width and depth) and the same terracotta tile roof. Each level is one storey taller and looks more valuable: the smallest is wood and plaster on a stone footing; the middle one has a solid stone ground floor, shutters, lanterns and iron fittings; the largest is mostly dressed stone with carved wooden beams, small gold finials on the roof tips and rich details.';
/**
 * Yard pattern (spec.layout "yard" of the first level): the smallest level occupies only about half of the plot,
 * next to it an open yard with fitting things (spec.yard); so the following levels can visibly grow.
 * spec.footprint [width, depth] in tiles from src/sim/data/buildings.js.
 */
export const SET_PATTERN_YARD = (fp, n) => [
  `All ${n} drawings show the SAME plot of land, ${fp[0]} units wide and ${fp[1]} units deep, drawn at the same scale and outlined by the building plus a low fence or wall; the plot ground is plain packed earth flush with the ground, no raised base plate.`,
  'The smallest stage covers only about HALF of the plot with its building; the rest of the plot is an open yard with the things described for it.',
  n >= 3 ? 'The middle stage covers about three quarters of the plot and is clearly bigger and taller.' : '',
  'The largest stage fills the WHOLE plot and is much bigger and taller than the smallest, so the upgrade is obvious from far above.',
  'All stages share the same terracotta tile roofs and get more valuable materials: wood and plaster, then stone, then dressed stone with gold finials.',
].filter(Boolean).join(' ');
const POSITION = { 1: ['The'], 2: ['Left', 'Right'], 3: ['Left', 'Middle', 'Right'], 4: ['First', 'Second', 'Third', 'Fourth'] };
async function conceptSet(ids, opts = {}) {
  const specs = ids.map(readSpec);
  // without icon (e.g. bridge parts): empty image 1, the description carries alone
  const icon = specs[0].icon ? await iconImage(specs[0].icon)
    : await sharp({ create: { width: 128, height: 128, channels: 3, background: '#e6e6e6' } }).png().toBuffer();
  const refHouse = path.join(DIR, 'house', 'concept.png');
  // spec.nature: nature object (tree, bush) – no house templates, otherwise the model paints a house in
  const nature = !!specs[0].nature;
  const refs = [await sharp(icon).resize(512).png().toBuffer(), await sharp(STYLE_HOUSE).resize(768).png().toBuffer(),
    ...(!nature && fs.existsSync(refHouse) && specs[0].icon !== 'b-residence' ? [await sharp(refHouse).resize(512).png().toBuffer()] : [])];
  // spec.refs: further templates (e.g. an already approved level), paths relative to assets-src/buildings, with spec.refsNote
  for (const r of specs[0].refs ?? []) refs.push(await sharp(path.join(DIR, r)).resize(512, 512, { fit: 'inside' }).png().toBuffer());
  const n = ids.length, yard = specs[0].layout === 'yard';
  const firstExtra = refs.length - (specs[0].refs?.length ?? 0) + 1;
  const prompt = [
    n === 1 ? 'Draw ONE building.' : `Draw ${n} growth stages of the SAME building side by side in one row, smallest on the left, largest on the right, all at the same scale, standing on the same baseline, with clear empty space between them.`,
    specs[0].icon ? 'Image 1 is a tiny game icon of the building: take its design (shape, materials, colors) from it.' : 'Image 1 is empty; follow the description.',
    specs[0].overall ?? '',
    ...specs.map((sp, i) => `${POSITION[n][i]} building: ${sp.describe ?? ''}`),
    // growth per building (spec.growth) instead of the uniform pattern; yard plot (layout "yard") first
    ...(specs[0].growth ? [yard ? SET_PATTERN_YARD(specs[0].footprint ?? [3, 3], n).split('. ')[0] + '.' : '', specs[0].growth]
      : [n > 1 ? (yard ? SET_PATTERN_YARD(specs[0].footprint ?? [3, 3], n) : SET_PATTERN) : '']),
    specs[0].refs?.length ? `Image ${firstExtra}${specs[0].refs.length > 1 ? ' and following' : ''}: ${specs[0].refsNote ?? 'approved related artwork of the same game'}.` : '',
    nature ? 'Image 2 defines ONLY the painting style – do NOT draw its house, draw no building at all: a polished stylized 3D asset for a PC medieval'
      : 'Image 2 defines ONLY the art style (ignore its yard, fence, grass and props): a polished stylized 3D asset for a PC medieval',
    'village-building strategy game, hand-painted game-model look – chunky slightly exaggerated proportions, thick wooden beams',
    'with rounded bevelled ends and painted grain, oversized roof tiles with painted highlights, cream plaster, light grey bevelled',
    'stone blocks, iron fittings, warm saturated natural colors, crisp clean edges, soft light from the upper left.',
    !nature && fs.existsSync(refHouse) && specs[0].icon !== 'b-residence' ? 'Image 3 is an approved building of the same game: match its style, level of detail and scale.' : '',
    'Not clay, not plasticine, not pastel, not photorealistic, no outlines.',
    'Each building alone, isometric three-quarter view from above (about 35°), front and one side visible, plain uniform light grey',
    yard ? 'background; the plot ground is flush packed earth, no raised base plate; no smoke, no people, no text, no numbers or digits, no labels.'
      : 'background, no ground, no base plate, no smoke, no people, no text, no numbers or digits under the buildings, no labels.',
    'Animals (horses, cows) are allowed only where described. No crosses or symbols of real religions.',
    specs[0].banner === false ? 'No banner, no flag, no pennant, no magenta anywhere (neutral building without owner).'
      : 'Each level has ONE cloth banner on a short pole on its roof in pure magenta (#FF00FF) as team color; magenta nowhere else.',
    'No blue anywhere (blue is a player color); all roofs in terracotta tiles.',
  ].filter(Boolean).join(' ');
  const { buf, cost } = await generateImage(opts.model ?? specs[0].imageModel ?? IMAGE_MODEL, prompt, refs, { aspect_ratio: n >= 3 ? '21:9' : n === 2 ? '16:9' : '1:1' });
  const setDir = path.join(DIR, ids[0]);
  let k = 1; while (fs.existsSync(path.join(setDir, `set-v${k}.png`))) k++;
  const setFile = path.join(setDir, `set-v${k}.png`);
  fs.writeFileSync(setFile, buf);
  // cut out like the character sheets: find columns with content
  const parts = await splitColumns(setFile, n);
  ids.forEach((id, i) => {
    const out = path.join(dirOf(id), 'concept.png');
    if (fs.existsSync(out)) { let m = 1; while (fs.existsSync(path.join(dirOf(id), `concept-v${m}.png`))) m++; fs.renameSync(out, path.join(dirOf(id), `concept-v${m}.png`)); }
    fs.writeFileSync(out, parts[i]);
    const job = loadJob(id);
    (job.concepts ??= []).push({ model: opts.model ?? IMAGE_MODEL, prompt, set: path.relative(DIR, setFile), part: i + 1, cost: i === 0 ? cost : 0 });
    if (job.model) { (job.oldModels ??= []).push(job.model); delete job.model; }
    saveJob(id, job);
  });
  console.log(setFile, cost ? `(${cost.toFixed(3)} $)` : '');
}

/** Split an image into n content columns (background from the corners), each column square with margin. */
async function splitColumns(file, n) {
  const { data, info } = await sharp(file).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const W = info.width, H = info.height, px = (x, y) => (y * W + x) * 3;
  const corners = [[2, 2], [W - 3, 2], [2, H - 3], [W - 3, H - 3]];
  const bg = [0, 1, 2].map((c) => corners.reduce((a, [x, y]) => a + data[px(x, y) + c], 0) / 4);
  const fg = (x, y) => Math.abs(data[px(x, y)] - bg[0]) + Math.abs(data[px(x, y) + 1] - bg[1]) + Math.abs(data[px(x, y) + 2] - bg[2]) > 45;
  const col = Array.from({ length: W }, (_, x) => { let c = 0; for (let y = 0; y < H; y += 2) if (fg(x, y)) c++; return c; });
  let runs = [], s = -1;
  for (let x = 0; x <= W; x++) { const on = x < W && col[x] > 2; if (on && s < 0) s = x; if (!on && s >= 0) { runs.push([s, x]); s = -1; } }
  // close small gaps within a building until n parts remain
  while (runs.length > n) {
    let best = 1; for (let i = 1; i < runs.length; i++) if (runs[i][0] - runs[i - 1][1] < runs[best][0] - runs[best - 1][1]) best = i;
    runs.splice(best - 1, 2, [runs[best - 1][0], runs[best][1]]);
  }
  if (runs.length < n) throw new Error(`Found only ${runs.length} of ${n} buildings in the image`);
  const out = [];
  for (const [x0, x1] of runs) {
    // take the tallest contiguous block (labels below the building drop out)
    const rowOn = (y) => { for (let x = x0; x < x1; x += 2) if (fg(x, y)) return true; return false; };
    let y0 = 0, y1 = -1, ys = -1, gap = 0;
    for (let y = 0; y <= H; y++) {
      const on = y < H && rowOn(y);
      if (on) { if (ys < 0) ys = y; gap = 0; continue; }
      if (ys >= 0 && (++gap > 12 || y === H)) { const e = y - gap; if (e - ys > y1 - y0) { y0 = ys; y1 = e; } ys = -1; }
    }
    const w = x1 - x0, h = y1 - y0 + 1, side = Math.round(Math.max(w, h) * 1.12);
    const crop = await sharp(file).extract({ left: x0, top: y0, width: w, height: h }).toBuffer();
    const sq = await sharp({ create: { width: side, height: side, channels: 3, background: { r: bg[0], g: bg[1], b: bg[2] } } })
      .composite([{ input: crop, left: Math.round((side - w) / 2), top: Math.round((side - h) / 2) }]).png().toBuffer();
    out.push(await sharp(sq).resize(1024, 1024).png().toBuffer());
  }
  return out;
}

/**
 * Back view for the concept (Seedream, ~0.02 $): the same building rotated by 180°, same style and scale.
 * If concept-back.png exists, Meshy gets both views (multi-image-to-3d) and does not invent the back.
 */
async function backView(id, opts = {}) {
  const spec = readSpec(id), dir = dirOf(id);
  const front = await sharp(path.join(dir, 'concept.png')).resize(768).png().toBuffer();
  const prompt = [
    'Image 1 shows a building of a stylized medieval strategy game. Draw EXACTLY the same building seen from the BACK:',
    'the camera has walked around it by 180 degrees, same isometric three-quarter view from above (about 35°), same scale, same position in the image.',
    `Keep every material, color, roof, tower, chimney${spec.banner === false ? '' : ' and the magenta banner'} identical; the back side shows plausible windows, walls and details that match the front.`,
    'The front door and front details are not visible from this side.',
    spec.describe ? `The building: ${spec.describe}` : '',
    'Same plain uniform light grey background, no ground plate, no text, no people.',
  ].filter(Boolean).join(' ');
  const { buf, cost } = await generateImage(opts.model ?? IMAGE_MODEL, prompt, [front], { aspect_ratio: '1:1' });
  fs.writeFileSync(path.join(dir, 'concept-back.png'), await sharp(buf).resize(1024, 1024).png().toBuffer());
  const job = loadJob(id);
  (job.backs ??= []).push({ model: opts.model ?? IMAGE_MODEL, prompt, cost });
  if (job.model) { (job.oldModels ??= []).push(job.model); delete job.model; }
  saveJob(id, job);
  console.log(path.join(dir, 'concept-back.png'), cost ? `(${cost.toFixed(3)} $)` : '');
}

/**
 * Winter version of a nature object: new folder <id>_winter with the same shape, bare or snowy (the game swaps
 * in winter). Deciduous trees without leaves with snow on the branches, conifers and bush snowy.
 */
async function winterView(id, opts = {}) {
  const spec = readSpec(id), dir = dirOf(id), out = `${id}_winter`, odir = path.join(DIR, out);
  const summer = await sharp(path.join(dir, 'concept.png')).resize(768).png().toBuffer();
  const evergreen = /spruce|pine/.test(id);
  const prompt = [
    'Image 1 shows a tree/plant of a stylized medieval strategy game. Draw EXACTLY the same object in deep WINTER:',
    'identical shape, silhouette, trunk, branch structure, size, position, camera and painting style.',
    evergreen ? 'It keeps its dark green needles, but thick soft white SNOW lies on top of every branch tier and the crown.'
      : id === 'bush' ? 'The bush has lost its leaves: a dense dome of bare, thin brown twigs, with soft white SNOW lying on top, no berries.'
        : 'It has lost ALL its leaves: show the bare branches and twigs of the same crown shape, with thick soft white SNOW lying on top of the branches and in the forks.',
    'Same plain uniform light grey background, no ground, no snow on the ground, no plate, no text, no people.',
  ].join(' ');
  const { buf, cost } = await generateImage(opts.model ?? IMAGE_MODEL, prompt, [summer], { aspect_ratio: '1:1' });
  fs.mkdirSync(odir, { recursive: true });
  fs.writeFileSync(path.join(odir, 'concept.png'), await sharp(buf).resize(1024, 1024).png().toBuffer());
  fs.writeFileSync(path.join(odir, 'spec.json'), JSON.stringify({ ...spec, $doc: `Winter version of ${id} (winter ${id})`, file: out, refs: [`${id}/concept.png`], winterOf: id }, null, 2));
  saveJob(out, { id: out, concepts: [{ model: opts.model ?? IMAGE_MODEL, prompt, cost, from: id }] });
  console.log(path.join(odir, 'concept.png'), cost ? `(${cost.toFixed(3)} $)` : '');
}

/** concept.png = chosen variant (concept-<name>.png). */
function pick(id, name) {
  const dir = dirOf(id), out = path.join(dir, 'concept.png');
  if (fs.existsSync(out)) { let n = 1; while (fs.existsSync(path.join(dir, `concept-v${n}.png`))) n++; fs.renameSync(out, path.join(dir, `concept-v${n}.png`)); }
  fs.copyFileSync(path.join(dir, `concept-${name}.png`), out);
  const job = loadJob(id);
  if (job.model) { (job.oldModels ??= []).push(job.model); delete job.model; }
  job.picked = name;
  saveJob(id, job);
}

async function model(id) {
  const spec = readSpec(id), dir = dirOf(id), job = loadJob(id);
  if (!job.model?.task) {
    spend(30, `${id}: building model`);
    // With back view (concept-back.png, see `back`): Meshy gets both sides (same price)
    const back = path.join(dir, 'concept-back.png');
    const multi = fs.existsSync(back);
    const base = {
      ai_model: 'meshy-7.1', should_texture: true, enable_pbr: true,
      should_remesh: true, topology: 'triangle', target_polycount: spec.polycount ?? 8000, remove_lighting: true,
      target_formats: ['glb'], origin_at: 'bottom',
    };
    const params = multi
      ? { ...base, image_urls: [dataUri(path.join(dir, 'concept.png')), dataUri(back)] }
      : { ...base, image_url: dataUri(path.join(dir, 'concept.png')) };
    const { result } = await meshy(multi ? 'v1/multi-image-to-3d' : 'v1/image-to-3d', params);
    job.model = { task: result, endpoint: multi ? 'v1/multi-image-to-3d' : 'v1/image-to-3d', params: { ...base, images: multi ? ['concept.png', 'concept-back.png'] : ['concept.png'] } };
    saveJob(id, job);
  }
  const t = await meshyWait(job.model.endpoint ?? 'v1/image-to-3d', job.model.task, { label: `${id} model` });
  await download(t.model_urls.glb, path.join(dir, 'raw.glb'));
  if (t.thumbnail_url) await download(t.thumbnail_url, path.join(dir, 'thumb.png'));
  job.model.credits = t.consumed_credits;
  saveJob(id, job);
  console.log(`\n${id}: raw.glb`);
}

/** Fill gaps between the UV islands (against light lines when downscaling), all meshes. */
function gutterLayers(doc, W, H, layers) {
  const uv = [], idx = [];
  for (const mesh of doc.getRoot().listMeshes()) for (const p of mesh.listPrimitives()) {
    const u = p.getAttribute('TEXCOORD_0')?.getArray(), ix = p.getIndices()?.getArray();
    if (!u || !ix) continue;
    const base = uv.length / 2;
    uv.push(...u);
    for (const i of ix) idx.push(i + base);
  }
  const id = rasterTriangles(new Float32Array(uv), new Uint32Array(idx), W, H);
  fillGutters(id, W, H, layers, W);
}

/** Magenta → player colour (brightness stays), sRGB 0–255. */
/**
 * Blue areas (slate roofs and bands from the icons) to terracotta: all buildings get the same tile roofs
 * as the house, and blue is a player colour. Brightness is matched to the tiles; magenta (team colour) stays.
 */
export function blueToTerracotta(buf) {
  for (let o = 0; o < buf.length; o += 3) {
    const r = buf[o], g = buf[o + 1], b = buf[o + 2];
    const mx = Math.max(r, g, b), mn = Math.min(r, g, b);
    if (mx !== b || mx - mn < 25) continue;
    // hue 190–260° (blue), softly faded; magenta and violet (red high) stay
    const d = mx - mn;
    const h = r >= g ? 240 + (60 * (r - g)) / d : 240 - (60 * (g - r)) / d;
    const w = Math.min(1, Math.max(0, Math.min(h - 190, 260 - h) / 15)) * Math.min(1, (d / mx - 0.15) / 0.15);
    if (w <= 0) continue;
    // tile tone (190, 85, 58) with the pixel's brightness; blue roofs are darker than tiles, hence × 1.4
    const l = (0.3 * r + 0.59 * g + 0.11 * b) * 1.4;
    const terra = [l * 1.67, l * 0.75, l * 0.51];
    for (let j = 0; j < 3; j++) buf[o + j] = Math.round(Math.min(255, buf[o + j] + (terra[j] - buf[o + j]) * w));
  }
}

export function recolorMarker(buf, color) {
  const tr = (color >> 16) & 255, tg = (color >> 8) & 255, tb = color & 255;
  const tv = Math.max(tr, tg, tb);
  for (let o = 0; o < buf.length; o += 3) {
    const w = markerWeight(buf[o], buf[o + 1], buf[o + 2]);
    if (!w) continue;
    const k = Math.max(buf[o], buf[o + 1], buf[o + 2]) / 255 * (255 / tv) * 0.9;
    const c = [tr * k, tg * k, tb * k];
    for (let j = 0; j < 3; j++) buf[o + j] = Math.round(Math.min(255, buf[o + j] + (c[j] - buf[o + j]) * w));
  }
}

/**
 * Game model: ONE file per model (public/models/buildings/<file>.glb). The pennant stays magenta; the game colours
 * it in the player colour when drawing (as with the characters). Texture 1024² (spec.textureSize), levels of detail without
 * their own texture (the game takes the material of the original).
 */
async function build(id) {
  const spec = readSpec(id), dir = dirOf(id);
  const size = spec.textureSize && spec.textureSize < 1024 ? spec.textureSize : 1024;
  fs.mkdirSync(OUT, { recursive: true });
  const doc = await io.read(path.join(dir, 'raw.glb'));
  const mat = doc.getRoot().listMaterials()[0];
  const baseTex = mat.getBaseColorTexture(), nrmTex = mat.getNormalTexture();
  const dec = async (t) => sharp(Buffer.from(t.getImage())).resize(size, size).removeAlpha().raw().toBuffer();
  const base = await dec(baseTex), nrm = nrmTex ? await dec(nrmTex) : null;
  gutterLayers(doc, size, size, [{ data: base, ch: 3 }, ...(nrm ? [{ data: nrm, ch: 3 }] : [])]);
  if (!spec.keepBlue) blueToTerracotta(base);
  const jpg = (b) => sharp(b, { raw: { width: size, height: size, channels: 3 } }).jpeg({ quality: 88, mozjpeg: true }).toBuffer();
  baseTex.setImage(await jpg(base)).setMimeType('image/jpeg');
  if (nrmTex) nrmTex.setImage(await jpg(nrm)).setMimeType('image/jpeg');
  // Meshy rotates some models: spec.rotate (degrees about the vertical axis) brings the entrance to the front like the other levels
  // models from two views are rotated by 90° at Meshy: compensate automatically (spec.rotate is added)
  const job0 = loadJob(id);
  const rotate = (spec.rotate ?? 0) + (job0.model?.endpoint === 'v1/multi-image-to-3d' ? 90 : 0);
  if (rotate) {
    const a = (rotate * Math.PI) / 360, q = [0, Math.sin(a), 0, Math.cos(a)];
    for (const n of doc.getRoot().getDefaultScene().listChildren()) {
      const [x, y, z, w] = n.getRotation();
      n.setRotation([q[3] * x + q[0] * w + q[1] * z - q[2] * y, q[3] * y - q[0] * z + q[1] * w + q[2] * x, q[3] * z + q[0] * y - q[1] * x + q[2] * w, q[3] * w - q[0] * x - q[1] * y - q[2] * z]);
      const [tx, ty, tz] = n.getTranslation(), c = Math.cos(2 * a), sn = Math.sin(2 * a);
      n.setTranslation([c * tx + sn * tz, ty, -sn * tx + c * tz]);
    }
  }
  mat.setMetallicRoughnessTexture(null).setEmissiveTexture(null).setOcclusionTexture(null).setMetallicFactor(0).setRoughnessFactor(0.85).setName(spec.file);
  await doc.transform(dedup(), prune(), meshopt({ encoder: MeshoptEncoder, level: 'medium' }));
  const file = path.join(OUT, `${spec.file}.glb`);
  await io.write(file, doc);
  // remove old versions per player colour
  for (const f of fs.readdirSync(OUT)) if (new RegExp(`^${spec.file}_(blue|red|green|yellow)(\\.lod\\d)?\\.glb$`).test(f)) fs.unlinkSync(path.join(OUT, f));
  // levels of detail (fewer triangles, without texture)
  execFileSync(process.execPath, [path.join(ROOT, 'scripts/build-lods.mjs'), file], { stdio: 'ignore' });
  console.log(`${path.basename(file)}: ${(fs.statSync(file).size / 1024).toFixed(0)} KB`);
}

const argv = process.argv.slice(2);
const flag = (n) => { const i = argv.indexOf(n); if (i < 0) return undefined; const v = argv[i + 1]; argv.splice(i, 2); return v; };
const opts = { model: flag('--model'), out: flag('--out'), effort: flag('--effort') };
const [cmd, id, arg] = argv;
if (import.meta.url === `file://${process.argv[1]}`) {
  requireAssetsSrc('buildings');
  reexecWithProxy();
  try {
    if (cmd === 'concept') await concept(id, opts);
    else if (cmd === 'set') await conceptSet(id.split(','), opts);
    else if (cmd === 'cut') { // cut out the chosen level set again: cut a,b,c set-v2
      const ids = id.split(','), parts = await splitColumns(path.join(DIR, ids[0], arg), ids.length);
      ids.forEach((x, i) => { fs.writeFileSync(path.join(dirOf(x), 'concept.png'), parts[i]); const job = loadJob(x); job.cut = arg; saveJob(x, job); });
    }
    else if (cmd === 'back') for (const x of id.split(',')) await backView(x, opts);
    else if (cmd === 'winter') for (const x of id.split(',')) await winterView(x, opts);
    else if (cmd === 'pick') pick(id, arg);
    else if (cmd === 'model') await model(id);
    else if (cmd === 'build') await build(id);
    else if (cmd === 'all') { await concept(id); await model(id); await build(id); }
    else { console.error('Usage: building.mjs concept|model|build|all <id>'); process.exit(1); }
  } catch (err) { console.error('\n' + err.message); process.exit(1); }
}
