import { test, expect } from '@playwright/test';
import { playUrl } from './paths.js';

// Painted ground textures (public/textures/ground/, generated by image AI): loaded before the game starts and replace
// the textures painted in code; without the files the game stays playable (fallback).

const painted = (page) => page.evaluate(() => {
  const u = window.__kronland.renderer.terrain.uniforms;
  return Object.fromEntries(['tGrass', 'tMeadow', 'tDirt', 'tSand', 'tRock', 'tSnow'].map((k) => [k, !!u[k].value.userData.painted]));
});

test('Ground from painted image files, at game height and up close', async ({ page }, info) => {
  const errors = [], loaded = [], failed = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('response', (r) => { if (r.url().includes('/textures/ground/')) (r.ok() ? loaded : failed).push(r.url().split('/').pop()); });
  await page.goto(playUrl('?seed=42'));
  await page.waitForFunction(() => !!window.__kronland?.renderer?.terrain);
  // Software WebGL of the tests = "low" level: the 512 versions
  expect(failed).toEqual([]);
  expect(loaded.length).toBe(6);
  expect(loaded.every((f) => f.endsWith('-512.webp'))).toBe(true);
  expect(Object.values(await painted(page)).every(Boolean)).toBe(true);
  await page.evaluate(() => {
    const e = window.__kronland, hq = e.sim.findBuilding(0, 'headquarters');
    e.renderer.rig.lookAt(hq.x + hq.w / 2 + 1, hq.y + hq.h + 1.5);
    e.renderer.rig.dist = 28;
  });
  await page.waitForTimeout(800);
  await page.screenshot({ path: `test-results/ground-gameheight-${info.project.name}.png` });
  await page.evaluate(() => { window.__kronland.renderer.rig.dist = 8; });
  await page.waitForTimeout(800);
  await page.screenshot({ path: `test-results/ground-near-${info.project.name}.png` });
  expect(errors).toEqual([]);
});

test('without image files: ground is painted in code as before', async ({ page }) => {
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  await page.route('**/textures/ground/**', (r) => r.abort());
  await page.goto(playUrl('?seed=42'));
  await page.waitForFunction(() => !!window.__kronland?.renderer?.terrain);
  expect(Object.values(await painted(page)).some(Boolean)).toBe(false);
  await expect(page.getByTestId('res-gold')).toHaveText('500');
  expect(errors).toEqual([]);
});
