// Scripting reference: language-neutral part, shared by the command help of the world editor (ApiHelp.vue) and the
// website section scripting/ (src/site/scripting/). Texts (descriptions, parameters, return values) live in
// src/ui/script/docs/de.js / en.js so the game bundle stays small.
//
// - BASICS: Python basics shown in the command help of the world editor.
// - PY_DOC: built-in Python functions, math, random and the methods of str/list/tuple/dict
//   (same shape as API_DOC in src/sim/scripting/api.js; `also` = further names explained in the same entry).
// - EXAMPLES: one example per entry (string, or { de, en } when the example contains readable text).
//   Python examples run in the VM on the website (output shown); game examples run in a test scenario
//   (tests/site/scripting.test.js) – an example that stops working fails the tests.
// - ERRORS: typical error codes per entry (texts from src/i18n/script.js).

import { siteUrl } from '../../paths.js';

/** Python basics (no game API) for the command help of the world editor. */
export const BASICS = [
  { name: 'py.print', sig: 'print("Hallo", x)', example: 'print("Hallo!")' },
  { name: 'py.var', sig: 'x = 5', example: 'count = 0' },
  { name: 'py.if', sig: 'if …: … elif …: … else: …', example: 'if nelia.can_step():\n    nelia.step()\nelse:\n    nelia.turn_left()' },
  { name: 'py.for', sig: 'for i in range(10):', example: 'for i in range(3):\n    nelia.step()' },
  { name: 'py.while', sig: 'while …:', example: 'while nelia.can_step():\n    nelia.step()' },
  { name: 'py.def', sig: 'def name(a, b):', example: 'def turn_around():\n    nelia.turn_left()\n    nelia.turn_left()' },
  { name: 'py.list', sig: '[1, 2, 3], xs.append(4), len(xs)', example: 'trees = trees_near(nelia)\nprint(len(trees))' },
  { name: 'py.dict', sig: '{"wood": 5}, d["wood"]', example: 'found = {}' },
  { name: 'py.fstring', sig: 'f"x = {x}"', example: 'print(f"Nelia steht bei {nelia.x}, {nelia.y}")' },
];

/** Anchors of the basics in the reference (chapter "language"). */
export const BASICS_ANCHOR = {
  'py.print': 'lang-print', 'py.var': 'lang-variables', 'py.if': 'lang-if', 'py.for': 'lang-for', 'py.while': 'lang-while',
  'py.def': 'lang-def', 'py.list': 'lang-lists', 'py.dict': 'lang-dicts', 'py.fstring': 'lang-strings',
};

/** Built-in Python functions, modules and methods. group: section of the reference. */
export const PY_DOC = [
  // Built-in functions
  { name: 'len', sig: 'len(obj)', group: 'pyfunc' },
  { name: 'range', sig: 'range(stop), range(start, stop, step=1)', group: 'pyfunc' },
  { name: 'int', sig: 'int(x=0, base=10)', group: 'pyfunc' },
  { name: 'float', sig: 'float(x=0)', group: 'pyfunc' },
  { name: 'str', sig: 'str(object="")', group: 'pyfunc' },
  { name: 'repr', sig: 'repr(obj)', group: 'pyfunc' },
  { name: 'bool', sig: 'bool(x=False)', group: 'pyfunc' },
  { name: 'list', sig: 'list(iterable=None)', group: 'pyfunc' },
  { name: 'tuple', sig: 'tuple(iterable=None)', group: 'pyfunc' },
  { name: 'dict', sig: 'dict(pairs=None, **values)', group: 'pyfunc' },
  { name: 'abs', sig: 'abs(x)', group: 'pyfunc' },
  { name: 'min', sig: 'min(iterable, key=None, default=…), min(a, b, …)', group: 'pyfunc', also: ['max'] },
  { name: 'sum', sig: 'sum(iterable, start=0)', group: 'pyfunc' },
  { name: 'sorted', sig: 'sorted(iterable, key=None, reverse=False)', group: 'pyfunc' },
  { name: 'reversed', sig: 'reversed(seq)', group: 'pyfunc' },
  { name: 'enumerate', sig: 'enumerate(iterable, start=0)', group: 'pyfunc' },
  { name: 'zip', sig: 'zip(*iterables)', group: 'pyfunc' },
  { name: 'map', sig: 'map(function, iterable, …)', group: 'pyfunc' },
  { name: 'filter', sig: 'filter(function, iterable)', group: 'pyfunc' },
  { name: 'any', sig: 'any(iterable), all(iterable)', group: 'pyfunc', also: ['all'] },
  { name: 'round', sig: 'round(number, ndigits=None)', group: 'pyfunc' },
  { name: 'divmod', sig: 'divmod(a, b)', group: 'pyfunc' },
  { name: 'pow', sig: 'pow(base, exp)', group: 'pyfunc' },
  { name: 'hex', sig: 'hex(x), bin(x), oct(x)', group: 'pyfunc', also: ['bin', 'oct'] },
  { name: 'chr', sig: 'chr(i), ord(c)', group: 'pyfunc', also: ['ord'] },
  { name: 'type', sig: 'type(object)', group: 'pyfunc' },
  { name: 'isinstance', sig: 'isinstance(obj, class)', group: 'pyfunc' },
  { name: 'callable', sig: 'callable(obj)', group: 'pyfunc' },
  { name: 'iter', sig: 'iter(obj), next(iterator, default=…)', group: 'pyfunc', also: ['next'] },
  { name: 'input', sig: 'input()', group: 'pyfunc' },
  { name: 'set', sig: 'set()', group: 'pyfunc' },
  // math
  { name: 'math.sqrt', sig: 'math.sqrt(x)', group: 'pymath' },
  { name: 'math.isqrt', sig: 'math.isqrt(n)', group: 'pymath' },
  { name: 'math.floor', sig: 'math.floor(x), math.ceil(x), math.trunc(x)', group: 'pymath', also: ['math.ceil', 'math.trunc'] },
  { name: 'math.fabs', sig: 'math.fabs(x)', group: 'pymath' },
  { name: 'math.hypot', sig: 'math.hypot(*coordinates)', group: 'pymath' },
  { name: 'math.dist', sig: 'math.dist(p, q)', group: 'pymath' },
  { name: 'math.gcd', sig: 'math.gcd(*integers)', group: 'pymath' },
  { name: 'math.pi', sig: 'math.pi, math.tau, math.e, math.inf, math.nan', group: 'pymath', also: ['math.tau', 'math.e', 'math.inf', 'math.nan'] },
  // random
  { name: 'random.random', sig: 'random.random()', group: 'pyrandom' },
  { name: 'random.randint', sig: 'random.randint(a, b)', group: 'pyrandom' },
  { name: 'random.randrange', sig: 'random.randrange(stop), random.randrange(start, stop, step=1)', group: 'pyrandom' },
  { name: 'random.choice', sig: 'random.choice(seq)', group: 'pyrandom' },
  { name: 'random.shuffle', sig: 'random.shuffle(x)', group: 'pyrandom' },
  { name: 'random.uniform', sig: 'random.uniform(a, b)', group: 'pyrandom' },
  { name: 'random.seed', sig: 'random.seed(a=0)', group: 'pyrandom' },
  // str
  { name: 'str.upper', sig: 's.upper(), s.lower(), s.capitalize(), s.title(), s.swapcase()', group: 'pystr', also: ['str.lower', 'str.capitalize', 'str.title', 'str.swapcase'] },
  { name: 'str.strip', sig: 's.strip(chars=None), s.lstrip(…), s.rstrip(…)', group: 'pystr', also: ['str.lstrip', 'str.rstrip'] },
  { name: 'str.split', sig: 's.split(sep=None, maxsplit=-1)', group: 'pystr' },
  { name: 'str.splitlines', sig: 's.splitlines()', group: 'pystr' },
  { name: 'str.join', sig: 'sep.join(iterable)', group: 'pystr' },
  { name: 'str.replace', sig: 's.replace(old, new, count=-1)', group: 'pystr' },
  { name: 'str.startswith', sig: 's.startswith(prefix), s.endswith(suffix)', group: 'pystr', also: ['str.endswith'] },
  { name: 'str.find', sig: 's.find(sub), s.rfind(sub)', group: 'pystr', also: ['str.rfind'] },
  { name: 'str.index', sig: 's.index(sub)', group: 'pystr' },
  { name: 'str.count', sig: 's.count(sub)', group: 'pystr' },
  { name: 'str.isdigit', sig: 's.isdigit(), s.isnumeric(), s.isalpha(), s.isalnum(), s.isspace(), s.isupper(), s.islower()', group: 'pystr', also: ['str.isnumeric', 'str.isalpha', 'str.isalnum', 'str.isspace', 'str.isupper', 'str.islower'] },
  { name: 'str.format', sig: 's.format(*args, **kwargs)', group: 'pystr' },
  { name: 'str.center', sig: 's.center(width, fillchar=" "), s.ljust(…), s.rjust(…)', group: 'pystr', also: ['str.ljust', 'str.rjust'] },
  { name: 'str.zfill', sig: 's.zfill(width)', group: 'pystr' },
  // list and tuple
  { name: 'list.append', sig: 'xs.append(object)', group: 'pylist' },
  { name: 'list.extend', sig: 'xs.extend(iterable)', group: 'pylist' },
  { name: 'list.insert', sig: 'xs.insert(index, object)', group: 'pylist' },
  { name: 'list.pop', sig: 'xs.pop(index=-1)', group: 'pylist' },
  { name: 'list.remove', sig: 'xs.remove(value)', group: 'pylist' },
  { name: 'list.index', sig: 'xs.index(value)', group: 'pylist' },
  { name: 'list.count', sig: 'xs.count(value)', group: 'pylist' },
  { name: 'list.sort', sig: 'xs.sort(key=None, reverse=False)', group: 'pylist' },
  { name: 'list.reverse', sig: 'xs.reverse()', group: 'pylist' },
  { name: 'list.copy', sig: 'xs.copy(), xs.clear()', group: 'pylist', also: ['list.clear'] },
  { name: 'tuple.index', sig: 't.index(value), t.count(value)', group: 'pylist', also: ['tuple.count'] },
  // dict
  { name: 'dict.keys', sig: 'd.keys(), d.values(), d.items()', group: 'pydict', also: ['dict.values', 'dict.items'] },
  { name: 'dict.get', sig: 'd.get(key, default=None)', group: 'pydict' },
  { name: 'dict.pop', sig: 'd.pop(key, default=…)', group: 'pydict' },
  { name: 'dict.setdefault', sig: 'd.setdefault(key, default=None)', group: 'pydict' },
  { name: 'dict.update', sig: 'd.update(other=None, **values)', group: 'pydict' },
  { name: 'dict.copy', sig: 'd.copy(), d.clear()', group: 'pydict', also: ['dict.clear'] },
];

/** Order of the sections: game API, then Python. */
export const API_GROUPS = ['flow', 'hero', 'world', 'village', 'story', 'events', 'goals', 'power', 'terrain', 'const'];
export const PY_GROUPS = ['pyfunc', 'pymath', 'pyrandom', 'pystr', 'pylist', 'pydict'];

const L = (de, en) => ({ de, en });

/** One example per entry. */
export const EXAMPLES = {
  // ---------- Flow ----------
  wait: 'nelia.say("Ich ruhe mich kurz aus.")\nwait(2)\nnelia.step()',
  wait_until: L(
    'ok = wait_until(lambda: stock("wood") >= 100, timeout=60)\nif ok:\n    print("Genug Holz!")\nelse:\n    print("Nach einer Minute immer noch zu wenig.")',
    'ok = wait_until(lambda: stock("wood") >= 100, timeout=60)\nif ok:\n    print("Enough wood!")\nelse:\n    print("Still too little after a minute.")',
  ),
  time: 'start = time()\nnelia.step(3)\nprint("Drei Schritte dauerten", round(time() - start, 1), "s")',
  print: 'wood = stock("wood")\nprint("Holz:", wood)\nprint(1, 2, 3, sep=" - ")',
  notify: L('wood = stock("wood")\nif wood >= 100:\n    notify(f"Genug Holz: {wood}")\nprint("Holz:", wood)', 'wood = stock("wood")\nif wood >= 100:\n    notify(f"Enough wood: {wood}")\nprint("Wood:", wood)'),
  // ---------- Hero ----------
  nelia: 'print(nelia, nelia.name, nelia.x, nelia.y)\nprint(orrin, orrin == nelia)',
  'nelia.step': 'nelia.step()\nnelia.step(2)',
  'nelia.turn_left': 'nelia.turn_left()\nprint(nelia.facing)',
  'nelia.turn_right': 'nelia.turn_right()\nnelia.turn_right()\nprint(nelia.facing)  # "west"',
  'nelia.turn_to': 'nelia.turn_to("north")\nwhile nelia.can_step():\n    nelia.step()',
  'nelia.front': 'what = nelia.front()\nif what == "coin":\n    nelia.step()\n    nelia.take()\nelif what == "tree":\n    nelia.turn_left()\nelse:\n    print("Vor mir:", what)',
  'nelia.left': 'if nelia.left() == "free":\n    nelia.turn_left()\n    nelia.step()\nprint("Rechts:", nelia.right())',
  'nelia.here': 'nelia.step()\nif nelia.here() == "coin":\n    nelia.take()\nprint("Hier:", nelia.here())',
  'nelia.can_step': 'steps = 0\nwhile nelia.can_step() and steps < 5:\n    nelia.step()\n    steps += 1\nprint(steps, "Schritte")',
  'nelia.move_to': 'nelia.move_to(place("goal"))\nnelia.move_to((5, 9))\nprint(nelia.is_at((5, 9)))',
  'nelia.is_at': 'nelia.move_to(place("goal"))\nif nelia.is_at(place("goal")):\n    nelia.say("Angekommen!")',
  'nelia.take': 'gold = stock("gold")\nif nelia.here() == "coin":\n    print("Aufgehoben:", nelia.take(), stock("gold") - gold)\nelse:\n    print("Hier liegt:", nelia.here())',
  'nelia.put': 'nelia.put()\nprint("Hier liegt:", nelia.here())\nnelia.step()\nnelia.put("coin")',
  'nelia.say': L('nelia.say("Hier lang!")', 'nelia.say("This way!")'),
  'nelia.facing': 'if nelia.facing != "north":\n    nelia.turn_to("north")',
  'nelia.x': 'print(f"Nelia steht bei ({nelia.x}, {nelia.y})")\nprint(tile(nelia.x + 1, nelia.y))',
  'nelia.use': L(
    'if nelia.ready("courage"):\n    nelia.use("courage")\nnelia.use("farsight", (nelia.x + 4, nelia.y))\nprint("Mut machen wieder in", nelia.cooldown("courage"), "s")',
    'if nelia.ready("courage"):\n    nelia.use("courage")\nnelia.use("farsight", (nelia.x + 4, nelia.y))\nprint("Rally again in", nelia.cooldown("courage"), "s")',
  ),
  'nelia.ready': 'for a in nelia.abilities():\n    print(a, nelia.ready(a), nelia.cooldown(a))\nnelia.use("farsight")\nwait_until(lambda: nelia.ready("farsight"), timeout=5)\nprint(nelia.cooldown("farsight"), "s")',
  'nelia.abilities': L(
    'print(nelia.abilities())\nfor a in nelia.abilities():\n    if nelia.ready(a):\n        print(a, "ist bereit")',
    'print(nelia.abilities())\nfor a in nelia.abilities():\n    if nelia.ready(a):\n        print(a, "is ready")',
  ),
  // ---------- World ----------
  place: 'goal = place("goal")\nprint(goal.x, goal.y, goal.r)\nnelia.move_to(goal)',
  places: 'for name in places():\n    p = place(name)\n    print(name, p.x, p.y)',
  tile: 'x, y = nelia.x, nelia.y\nfor dx in range(1, 4):\n    print(x + dx, y, tile(x + dx, y))',
  distance: 'd = distance(nelia, place("goal"))\nprint("Noch", round(d, 1), "Kacheln")',
  'obj.distance_to': 'trees = trees_near(nelia, radius=20)\nif trees:\n    print(round(trees[0].distance_to(nelia), 1))',
  'place.contains': 'camp = place("camp")\nprint(camp.contains(nelia))\nprint(camp.contains((camp.x, camp.y)))',
  trees_near: 'trees = trees_near(hq(), radius=12)\nprint(len(trees), "Bäume in der Nähe")\nif trees:\n    t = trees[0]\n    print("Der nächste steht bei", t.x, t.y, "mit", t.amount, "Holz")',
  piles_near: 'for p in piles_near(hq(), radius=20, res="stone"):\n    print(p, p.amount)',
  figures_near: 'for f in figures_near(nelia, radius=10, side="own"):\n    print(f.kind, f.x, f.y)\nenemies = figures_near(hq(), 20, side="enemy")\nprint(len(enemies), "Feinde in der Nähe")',
  items_near: 'coins = items_near(nelia, radius=10, kind="coin")\nif coins:\n    nelia.move_to(coins[0])\n    nelia.take()\nprint(len(coins), "Taler in der Nähe")',
  weather: 'if weather() == "winter":\n    print("Das Wasser ist gefroren und trägt.")\nelse:\n    print("Wetter:", weather())',
  forecast: 'if count("weatherTower") > 0:\n    for state, seconds in forecast():\n        print(state, "in", seconds, "s")\nelse:\n    print("Ohne Wetterturm keine Vorhersage")',
  // ---------- Village ----------
  stock: 'for res in ["wood", "clay", "stone", "iron", "sulfur", "gold"]:\n    print(res, stock(res))',
  count: 'print("Wohnhäuser:", count("residence"))\nprint("mit Baustellen:", count("residence", placed=True))\nprint("Leibeigene:", count("serf"), "Trupps:", count("troop"))',
  serfs: 'idle = serfs(idle=True)\nprint(len(idle), "von", len(serfs()), "Leibeigenen haben nichts zu tun")',
  troops: 'for t in troops():\n    print(t.type, t.soldiers, "Soldaten bei", t.x, t.y)',
  buildings: 'for b in buildings("residence"):\n    print(b, "Stufe", b.level, "fertig" if b.done else "im Bau")',
  hq: 'castle = hq()\nif castle:\n    print("Burg bei", castle.x, castle.y, "mit", castle.hp, "Lebenspunkten")',
  find_spot: 'spot = find_spot("farm", hq(), radius=15)\nif spot:\n    x, y = spot\n    print("Platz für einen Bauernhof:", x, y)',
  can_build: 'spot = find_spot("residence", hq())\nif spot and can_build("residence", spot[0], spot[1]):\n    build("residence", spot[0], spot[1])',
  build: 'x, y = find_spot("residence", hq())\nsite = build("residence", x, y)\nfor s in serfs(idle=True)[:3]:\n    s.work_on(site)',
  buy_serf: 'if stock("gold") >= 200 and count("villageCenter") > 0:\n    buy_serf(2)\nprint(count("serf"), "Leibeigene")',
  'serf.chop': 's = serfs()[0]\nfor i in range(4):\n    if s.front() == "tree":\n        s.chop()\n        break\n    s.turn_left()\nprint("Holz:", stock("wood"))',
  'serf.work_on': 'trees = trees_near(hq(), radius=15)\nfor s, t in zip(serfs(idle=True), trees):\n    s.work_on(t)',
  'troop.attack': 'for t in troops():\n    if t.soldiers >= 3:\n        t.attack(place("camp"))',
  'troop.hold': 'for t in troops():\n    t.hold()\nwait(5)\nfor t in troops():\n    t.defend()\nprint(len(troops()), "Trupps")',
  call_to_arms: L(
    '@on_event("attacked")\ndef alarm(target, attacker):\n    call_to_arms()\n    if nelia.ready("courage"):\n        nelia.use("courage")\n\nprint(call_to_arms(serfs()[:1]), "Leibeigener an den Waffen")\nwait(5)\nback_to_work()\nprint([s.militia for s in serfs()])',
    '@on_event("attacked")\ndef alarm(target, attacker):\n    call_to_arms()\n    if nelia.ready("courage"):\n        nelia.use("courage")\n\nprint(call_to_arms(serfs()[:1]), "serf took up arms")\nwait(5)\nback_to_work()\nprint([s.militia for s in serfs()])',
  ),
  'building.change_weather': 'for plant in buildings("weatherPlant"):\n    if plant.can_change_weather("winter"):\n        plant.change_weather("winter")\nprint(weather(), stock("energy"))',
  'building.upgrade': 'for b in buildings("residence"):\n    if b.done and b.level == 1:\n        b.upgrade()\n        break',
  // ---------- Staging ----------
  say: 'say("nelia", de="Da hinten liegt das Lager der Räuber.", en="The bandit camp is over there.")\nsay("kunz", "Kommt nur her!", seconds=3)\nsay("nelia", de="Leise jetzt.", en="Quiet now.", wait=False)',
  message: 'message(de="Ein Händler ist eingetroffen.", en="A merchant has arrived.")',
  npc: 'alchemist = npc("alchemist", look="worker.alchemist", at=place("camp"), name="Alchemist")\nprint(alchemist, alchemist.talkable)\nstranger = npc("stranger", look="hero.orrin", at=place("goal"), speaker="orrin")',
  'npc.stop_talking': 'alchemist = npc("alchemist", look="worker.alchemist", at=place("camp"))\n\n@on_talk("alchemist")\ndef talk(hero):\n    say("alchemist", de="Schwefel? Im Norden.", en="Sulfur? Up north.")\n    alchemist.stop_talking()',
  'camera.jump_to': 'camera.jump_to(hq())',
  'camera.fly_to': 'camera.fly_to(place("camp"), seconds=3)\ncamera.fly_to(nelia, seconds=2)',
  reveal: 'reveal(place("camp"), radius=8, seconds=20)',
  // ---------- Events ----------
  on_start: L('@on_start\ndef intro():\n    camera.jump_to(hq())\n    say("nelia", "Willkommen in Kronland!")', '@on_start\ndef intro():\n    camera.jump_to(hq())\n    say("nelia", "Welcome to Kronland!")'),
  every: L(
    'checks = 0\n\n@every(5)\ndef report():\n    global checks\n    checks += 1\n    print("Runde", checks, "– Holz:", stock("wood"))\n\nprint("Ich schaue alle 5 Sekunden ins Lager.")',
    'checks = 0\n\n@every(5)\ndef report():\n    global checks\n    checks += 1\n    print("Round", checks, "– wood:", stock("wood"))\n\nprint("I check the storehouse every 5 seconds.")',
  ),
  on_building_done: L('@on_building_done("farm")\ndef farm_ready(building):\n    notify("Der Bauernhof ist fertig!")\n    print(building.type, "auf", building.x, building.y)', '@on_building_done("farm")\ndef farm_ready(building):\n    notify("The farm is finished!")\n    print(building.type, "at", building.x, building.y)'),
  on_building_placed: L('@on_building_placed\ndef placed(building):\n    for s in serfs(idle=True)[:2]:\n        s.work_on(building)\n\nspot = find_spot("residence", hq())\nbuild("residence", spot[0], spot[1])', '@on_building_placed\ndef placed(building):\n    for s in serfs(idle=True)[:2]:\n        s.work_on(building)\n\nspot = find_spot("residence", hq())\nbuild("residence", spot[0], spot[1])'),
  on_destroyed: L('@on_destroyed("residence")\ndef lost(kind, owner):\n    notify("Ein Wohnhaus ist verloren!")', '@on_destroyed("residence")\ndef lost(kind, owner):\n    notify("A residence is lost!")'),
  on_killed: L('losses = 0\n\n@on_killed\ndef fallen(kind, owner):\n    global losses\n    losses += 1\n    print("Verluste:", losses, kind)', 'losses = 0\n\n@on_killed\ndef fallen(kind, owner):\n    global losses\n    losses += 1\n    print("Losses:", losses, kind)'),
  on_recruited: L('@on_recruited\ndef recruited(troop):\n    print("Neuer Trupp:", troop.type)\n    troop.move_to(place("gate"), wait=False)', '@on_recruited\ndef recruited(troop):\n    print("New troop:", troop.type)\n    troop.move_to(place("gate"), wait=False)'),
  on_research: L('@on_research("conscription")\ndef researched(tech):\n    notify("Jetzt kannst du eine Kaserne bauen.")', '@on_research("conscription")\ndef researched(tech):\n    notify("Now you can build a barracks.")'),
  on_enter: L('@on_enter(place("gate"), who="hero")\ndef arrived(unit):\n    print(unit.name, "ist am Tor")\n\nnelia.move_to(place("gate"))', '@on_enter(place("gate"), who="hero")\ndef arrived(unit):\n    print(unit.name, "is at the gate")\n\nnelia.move_to(place("gate"))'),
  on_objective: L('@on_objective("camp", status="done")\ndef done(id, status):\n    notify("Ziel geschafft: " + id)', '@on_objective("camp", status="done")\ndef done(id, status):\n    notify("Objective done: " + id)'),
  on_weather: L('@on_weather("winter")\ndef cold(state):\n    notify("Die Flüsse frieren zu – jetzt geht es übers Eis!")', '@on_weather("winter")\ndef cold(state):\n    notify("The rivers are freezing – now we can cross the ice!")'),
  on_talk: 'npc("alchemist", look="worker.alchemist", at=place("camp"))\n\n@on_talk("alchemist")\ndef talk(visitor):\n    if visitor.name != "orrin":\n        say("alchemist", de="Schick mir den Händler.", en="Send me the merchant.")\n        return\n    say("alchemist", de="Schwefel? Im Norden, hinter dem Grat.", en="Sulfur? Up north, behind the ridge.")',
  on_event: L('@on_event("every", seconds=30)\ndef report():\n    print("Holz:", stock("wood"))\n\n@on_event("enter", target=place("camp"), who="hero")\ndef found(unit):\n    notify("Am Lager angekommen.")', '@on_event("every", seconds=30)\ndef report():\n    print("Wood:", stock("wood"))\n\n@on_event("enter", target=place("camp"), who="hero")\ndef found(unit):\n    notify("Arrived at the camp.")'),
  // ---------- Goals ----------
  objective: 'objective("homes", lambda: (count("residence"), 3), de="Baue 3 Wohnhäuser", en="Build 3 residences")\nobjective("gold", lambda: stock("gold") >= 1000, de="Spare 1000 Gold", en="Save 1000 gold", primary=False)',
  complete: 'objective("scout", de="Erkunde das Lager", en="Scout the camp")\n\n@on_enter(place("camp"), who="hero")\ndef scouted(unit):\n    complete("scout")',
  fail: 'objective("escort", de="Bringe Orrin sicher heim", en="Bring Orrin home safely")\n\n@on_killed(HUMAN)\ndef check(kind, owner):\n    if orrin and orrin.down:\n        fail("escort")',
  show_objective: 'objective("camp", de="Zerstöre das Räuberlager", en="Destroy the bandit camp", hidden=True)\nwait(30)\nshow_objective("camp")',
  ending: '# der Weg des Spielers wählt die Nachgeschichte (debriefs in scenario.json)\nending("stormed")',
  victory: 'wait_until(lambda: len(buildings("banditCamp", BANDITS)) == 0)\nvictory("camp", de="Das Lager ist zerstört!", en="The camp is destroyed!")',
  'program.get': 'objective("guess", lambda: program.status == "done" and program.get("steps") == 7,\n          de="Wie viele Schritte braucht Nelia? Speichere die Zahl in steps.", en="How many steps does Nelia need? Store the number in steps.")\n\n@on_start\ndef watch():\n    wait_until(lambda: program.runs > 0)\n    print("Erster Lauf, Zustand:", program.status)',
  hints: 'hints(False)  # in dieser Etappe ist das Finden des Fehlers die Aufgabe',
  note: L(
    'npc("maid", look="serf", at=place("camp"), name="Magd Hedda")\n\n@on_start\ndef hand_over():\n    say("maid", de="Hier, nimm den Zettel. Wie viele Schritte sind es?", en="Here, take the note. How many steps is it?")\n    note("maid", "guess = 0\\nsteps = 0\\nwhile nelia.can_step():\\n    nelia.step()\\n    steps = steps + 1\\n", de="Zettel der Magd", en="The maid\'s note")',
    'npc("maid", look="serf", at=place("camp"), name="Maid Hedda")\n\n@on_start\ndef hand_over():\n    say("maid", de="Hier, nimm den Zettel. Wie viele Schritte sind es?", en="Here, take the note. How many steps is it?")\n    note("maid", "guess = 0\\nsteps = 0\\nwhile nelia.can_step():\\n    nelia.step()\\n    steps = steps + 1\\n", de="Zettel der Magd", en="The maid\'s note")',
  ),
  reset: L(
    'reset(False)  # Aufbau-Mission: Ausführen baut weiter, statt neu zu beginnen\nobjective("homes", lambda: (count("residence"), 3), de="Baue 3 Wohnhäuser", en="Build 3 residences")',
    'reset(False)  # building mission: Run builds on instead of starting over\nobjective("homes", lambda: (count("residence"), 3), de="Baue 3 Wohnhäuser", en="Build 3 residences")',
  ),
  defeat: 'wait_until(lambda: not nelia.alive or nelia.down)\ndefeat("hero")',
  // ---------- Intervening ----------
  spawn: 'guards = spawn(BANDITS, "spear1", place("camp"), count=2, soldiers=3)\nprint(len(guards), "Trupps bewachen das Lager")',
  spawn_serfs: 'new = spawn_serfs(HUMAN, 4)\nfor s in new:\n    print(s, s.idle)',
  give: 'give(HUMAN, wood=300, stone=100)\ngive(HUMAN, gold=-50)\ngive(ENEMY, energy=1000)  # Wetterkraftwerk geladen\nprint(stock("wood"), stock("gold"))',
  set_diplomacy: 'set_diplomacy(HUMAN, ENEMY, "neutral")\nprint(diplomacy(HUMAN, ENEMY))',
  diplomacy: 'if diplomacy(HUMAN, BANDITS) == "hostile":\n    print("Vorsicht vor den Räubern!")',
  give_tech: 'give_tech(HUMAN, "conscription", "construction")',
  place_building: 'camp = place_building(BANDITS, "banditCamp", place("camp"))\nprint(camp, camp.hp, camp.max_hp)\nsite = place_building(HUMAN, "farm", hq(), done=False)\ntower = place_building(ENEMY, "residence", place("gate"), level=1, min_r=2, radius=8, fixed=True)',
  remove: 'stranger = npc("stranger", look="hero.orrin", at=place("goal"))\nwait(5)\nremove(stranger)  # spurlos, ohne Ereignis\nadd_hero(HUMAN, "orrin", place("goal"))',
  'nelia.teleport': 'nelia.teleport(place("goal"))\nprint(nelia.x, nelia.y)\nfor s in serfs():\n    s.teleport(place("gate"))',
  'obj.kill': 'for t in troops(BANDITS):\n    t.kill()',
  attack: 'wave = spawn(BANDITS, "sword1", place("gate"), count=3)\nattack(wave, hq())',
  move: 'move(troops(), place("gate"))',
  alive: 'wave = spawn(BANDITS, "sword1", place("gate"), count=3)\nattack(wave, hq())\nwait_until(lambda: alive(wave) == 0)\nmessage("Angriff abgewehrt!")',
  hero_of: 'o = hero_of(HUMAN, "orrin")\nif o is None:\n    print("Orrin ist nicht dabei.")\nenemy = hero_of(ENEMY)\nprint(enemy)',
  set_weather: 'set_weather("winter", seconds=90)',
  ai: 'ai(ENEMY, difficulty="hard", aggression="passive", start_in=120, forbid=["weatherPlant"])',
  // ---------- Terrain ----------
  make_place: 'make_place("well", 20, 14, r=2)\nnelia.move_to(place("well"))',
  find_open: 'spot = find_open(map_center(), min_r=4, max_r=16)\nif spot:\n    make_place("ruins", spot.x, spot.y, 3)\ncamp_spot = find_open(place("camp"), max_r=12, clear=3, reachable_from=hq(), avoid=[place("goal")])',
  add_ruin: 'ruin = add_ruin("residence", place("camp"))\nprint(ruin)',
  add_shaft: 'shaft = add_shaft("clay", hq())\nif shaft:\n    make_place("clay", shaft.x, shaft.y, 2)\n    print("Lehm bei", shaft.x, shaft.y)',
  convert: 'deserters = spawn(BANDITS, "sword1", place("gate"))\nprint(convert(deserters, HUMAN), "Trupp läuft über")',
  add_hero: 'add_hero(HUMAN, "orrin", place("goal"))\nprint(orrin.name, orrin.x, orrin.y)',
  camp: 'guards = camp("outpost", place("camp"), [("spear1", 2, 3)], r=6)\nprint(len(guards), "Wachen bei", place("outpost"))',
  player: 'robbers = player("bandits")\nprint(robbers == BANDITS, player("human"))',
  unlock: '@on_research("conscription")\ndef army(tech):\n    unlock("barracks", "standingArmy")',
  withdraw: 'offer("help", {"wood": 200}, de="Holz für das Nachbardorf", en="Wood for the village next door")\nwait(60)\nwithdraw("help")',
  offer: 'offer("toll", {"gold": 100}, de="Wegzoll an die Räuber", en="Toll for the bandits")\n\n@on_event("tribute", id="toll")\ndef paid(id):\n    set_diplomacy(HUMAN, BANDITS, "neutral")',
  hint: 'objective("farm", lambda: (count("farm"), 1), de="Baue einen Bauernhof", en="Build a farm")\nhint("farm", area="goal", ui=["build-farm", "quick-all"],\n     ui_until=lambda: count("farm", placed=True) >= 1)',
  step: 'step("look", next=True, title={"de": "Umsehen", "en": "Look around"},\n     de="Schau dich im Tal um.", en="Have a look around the valley.")\nresult = step("work", until=lambda: len(serfs(idle=True)) == 0, hint={"ui": "quick-all"},\n              de="Gib allen Leibeigenen Arbeit.", en="Give every serf some work.")\nprint(result)',
  researched: 'if researched("conscription"):\n    print("Die Kaserne ist erforscht.")',
  toward: 'mid = toward(hq(), map_center(), 10)\nmake_place("outpost", mid.x, mid.y, 3)',
  start_spot: 's = start_spot()\nprint(s.x, s.y, start_spot(ENEMY))',
  map_center: 'c = map_center()\nprint(c.x, c.y)\ncamera.jump_to(c)',
  plant_trees: 'n = plant_trees((26, 12), 25, radius=5)\nprint(n, "Bäume gepflanzt")',
  add_tree: 'for x in range(10, 20, 2):\n    add_tree(x, 30)\nadd_tree(21, 30, amount=2)  # ein junger Baum',
  add_pile: 'add_pile("stone", 20, 24, amount=400)\nadd_pile("clay", 24, 22)',
  clear_area: 'clear_area(place("camp"), 5)',
  add_item: 'for x in range(5, 12):\n    add_item("coin", x, 20)\nadd_item("flower", 4, 22)\nprint(len(items("coin")), "Taler")',
  remove_item: 'add_item("coin", 6, 20)\nprint(remove_item(6, 20), remove_item(6, 20))',
  items: 'add_item("coin", 6, 20)\nadd_item("flower", 7, 20)\nprint(items(), items("coin"))\nobjective("coins", lambda: not items("coin"), de="Sammle alle Taler", en="Collect all thalers")',
  'world.set_track': 'for x in range(5, 15):\n    world.set_track(x, 20)\nworld.set_track(15, 20, 0)\nprint(tile(5, 20), tile(15, 20))',
  'world.id': '# Weltcode: Normalfall und Randfall aus demselben Code (ohne "worlds" ist world.id None)\nif world.id == "near":\n    add_item("coin", 5, 5)\nelse:\n    add_item("coin", 9, 5)\nprint("Welt:", world.id, "– gestartet bei Etappe:", world.stage)',
  'objective_status': 'objective("coin", lambda: len(items("coin")) == 0, de="Heb den Taler auf", en="Pick up the coin")\n\n@on_start\ndef story():\n    wait_until(lambda: objective_status("coin") != "active")\n    print("Ziel coin:", objective_status("coin"))',
  'world.width': 'print(world.width, "×", world.height, "Kacheln")\nprint("Wasserspiegel:", world.water_level)',
  'world.height_at': 'h = world.height_at(10, 10)\nprint("Höhe:", h, "cm")',
  'world.is_water': 'water = 0\nfor x in range(world.width):\n    if world.is_water(x, 20):\n        water += 1\nprint(water, "Wasserkacheln in Zeile 20")',
  'world.set_height': '# kleiner Hügel um (30, 30)\nfor dx in range(-3, 4):\n    for dy in range(-3, 4):\n        d = abs(dx) + abs(dy)\n        world.set_height(30 + dx, 30 + dy, 600 - d * 100)',
  'world.set_water': '# ein Bach quer über die Karte\nfor y in range(world.height):\n    world.set_water(36, y)',
  'world.set_cliff': 'for x in range(5, 12):\n    world.set_cliff(x, 40)',
  'world.reachable': 'print(world.reachable(hq(), place("camp")))\nprint(world.reachable(hq(), place("camp"), frozen=True))',
  'world.nearest_walkable': 'p = world.nearest_walkable(hq())\nprint(p.x, p.y)',
  'world.axis_point': 'a = hq()\nb = map_center()\np = world.axis_point(a, b, 10, side=3)\nprint(p, world.axis_coords(a, b, p))',
  'world.soften': 'world.soften(divide=2)',
  'world.ridge': '# ein Bergkamm zwischen Burg und Lager, mit einem Pass\nridge = world.ridge(hq(), place("camp"), 12, 3)\ngap = world.ridge_gap(ridge, 0, width=4)\nprint(world.reachable(hq(), place("camp")))',
  'world.ridge_gap': 'ridge = world.ridge(hq(), place("camp"), 12, 3)\npass_ = world.ridge_gap(ridge, 0, width=4)\ngorge = world.ridge_gap(ridge, -12, water=True)\nprint(pass_["center"], gorge["near"], gorge["far"])',
  'world.channel': '# ein Bach vom Lager zum Tor\nworld.channel(place("camp"), place("gate"), width=2)',
  'world.lake_island': 'isle = world.lake_island((30, 32), inner=4, width=3)\nprint(isle.r, world.reachable(hq(), isle, frozen=False), world.reachable(hq(), isle, frozen=True))',
  'world.moat': 'isle = None\nfor inner in range(6, 12):\n    isle = world.moat(hq(ENEMY), hq(), inner=inner, width=3)\n    if isle:\n        break\nprint(isle)',
  'world.island': 'isle = world.island(hq(), hq(ENEMY), inner=3, width=2, min_dist=14)\nprint(isle)',
  'world.noise': 'for x in range(0, 48):\n    for y in range(0, 48):\n        n = world.noise(x, y, cell=16)\n        if n > 900:\n            add_tree(x, y)',
  // ---------- Constants ----------
  HUMAN: 'print(HUMAN, ENEMY, BANDITS)\nprint(stock("gold", HUMAN))',

  // ---------- Python: built-in functions ----------
  len: 'stock = {"wood": 120, "stone": 40}\nprint(len(stock))\nprint(len("Kronland"), len([3, 1, 4]))',
  range: 'print(list(range(5)))\nprint(list(range(2, 10, 3)))\nfor i in range(3, 0, -1):\n    print(i)',
  int: 'print(int("42") + 1)\nprint(int(3.9), int(-3.9))\nprint(int("ff", 16), int("101", 2))',
  float: 'print(float("2.5") * 2)\nprint(float(7))\nprint(7 / 2, float("inf"))',
  str: 'wood = 120\nprint("Holz: " + str(wood))\nprint(str(3.5), str(True), str(None))',
  repr: 'print(repr("wood"), repr([1, "a"]))\nprint(str("wood"))',
  bool: 'print(bool(0), bool(3), bool(""), bool("x"))\nprint(bool([]), bool([0]), bool(None))',
  list: 'print(list("abc"))\nprint(list(range(4)))\nprint(list({"wood": 1, "gold": 2}))',
  tuple: 'pos = tuple([4, 7])\nx, y = pos\nprint(pos, x, y)',
  dict: 'costs = dict(wood=150, stone=100)\nprint(costs)\nprint(dict([("gold", 50), ("iron", 10)]))',
  abs: 'print(abs(-7), abs(2.5))\ndx = 3 - 10\nprint("Abstand in x:", abs(dx))',
  min: 'print(min(4, 1, 7), max([4, 1, 7]))\nwords = ["wood", "iron", "sulfur"]\nprint(max(words, key=len))\nprint(min([], default=0))',
  sum: 'harvest = [12, 30, 8]\nprint(sum(harvest))\nprint(sum([0.5, 0.25], 1))',
  sorted: 'stock = {"wood": 120, "stone": 40, "gold": 300}\nprint(sorted(stock))\nprint(sorted(stock, key=lambda r: stock[r], reverse=True))',
  reversed: 'print(list(reversed([1, 2, 3])))\nfor c in reversed("abc"):\n    print(c)',
  enumerate: 'for i, res in enumerate(["wood", "clay", "stone"], start=1):\n    print(i, res)',
  zip: 'names = ["wood", "stone"]\namounts = [120, 40]\nfor n, a in zip(names, amounts):\n    print(n, a)\nprint(dict(zip(names, amounts)))',
  map: 'print(list(map(str, [1, 2, 3])))\nprint(list(map(lambda x: x * 2, [1, 2, 3])))',
  filter: 'amounts = [0, 12, 0, 40]\nprint(list(filter(lambda a: a > 0, amounts)))\nprint(list(filter(None, amounts)))',
  any: 'amounts = [0, 12, 40]\nprint(any(a > 30 for a in amounts))\nprint(all(a > 0 for a in amounts))',
  round: 'print(round(2.675, 2), round(3.14159, 3))\nprint(round(2.5), round(3.5), round(1234, -2))',
  divmod: 'seconds = 135\nminutes, rest = divmod(seconds, 60)\nprint(minutes, "min", rest, "s")',
  pow: 'print(pow(2, 10), 2 ** 10)\nprint(pow(2, -1))',
  hex: 'print(hex(255), bin(5), oct(8))\nprint(int("0xff", 16))',
  chr: 'print(ord("A"), chr(66))\nprint("".join(chr(ord("a") + i) for i in range(5)))',
  type: 'print(type(5), type(2.5), type("x"))\nprint(type([]) == list)',
  isinstance: 'for v in [3, 2.5, "3", True]:\n    print(repr(v), isinstance(v, int), isinstance(v, (int, float)))',
  callable: 'def greet():\n    return "Hallo"\nprint(callable(greet), callable(print), callable(5))',
  iter: 'it = iter([10, 20])\nprint(next(it))\nprint(next(it))\nprint(next(it, "fertig"))',
  input: '# input() gibt es nicht – Werte stehen direkt im Programm:\nname = "Nelia"\nprint("Hallo", name)',
  set: '# set() gibt es nicht – eine Liste oder ein Wörterbuch tut es auch:\nseen = []\nfor x in [3, 1, 3, 2, 1]:\n    if x not in seen:\n        seen.append(x)\nprint(seen)',
  // ---------- Python: math ----------
  'math.sqrt': 'import math\nprint(math.sqrt(16), math.sqrt(2))\nx, y = 3, 4\nprint(math.sqrt(x * x + y * y))',
  'math.isqrt': 'import math\nprint(math.isqrt(17), math.isqrt(16))',
  'math.floor': 'import math\nprint(math.floor(2.7), math.ceil(2.1), math.trunc(-2.7))\nprint(math.floor(-2.7))',
  'math.fabs': 'import math\nprint(math.fabs(-3), abs(-3))',
  'math.hypot': 'import math\nprint(math.hypot(3, 4))\nprint(math.hypot(1, 2, 2))',
  'math.dist': 'import math\nprint(math.dist((1, 2), (4, 6)))',
  'math.gcd': 'import math\nprint(math.gcd(12, 18), math.gcd(7, 5))',
  'math.pi': 'import math\nr = 3\nprint(round(math.pi * r * r, 2))\nprint(math.tau, math.e)\nprint(math.inf > 10 ** 100, math.nan == math.nan)',
  // ---------- Python: random ----------
  'random.random': 'import random\nrandom.seed(7)\nif random.random() < 0.25:\n    print("Glück gehabt!")\nprint(random.random())',
  'random.randint': 'import random\nrandom.seed(3)\nprint([random.randint(1, 6) for i in range(5)])',
  'random.randrange': 'import random\nrandom.seed(4)\nprint(random.randrange(10), random.randrange(0, 100, 10))',
  'random.choice': 'import random\nrandom.seed(2)\nprint(random.choice(["wood", "clay", "stone"]))',
  'random.shuffle': 'import random\nrandom.seed(5)\norder = [1, 2, 3, 4, 5]\nrandom.shuffle(order)\nprint(order)',
  'random.uniform': 'import random\nrandom.seed(6)\nprint(round(random.uniform(1.5, 2.5), 3))',
  'random.seed': 'import random\nrandom.seed(42)\na = random.randint(1, 100)\nrandom.seed(42)\nb = random.randint(1, 100)\nprint(a == b)',
  // ---------- Python: str ----------
  'str.upper': 'name = "nelia von kronland"\nprint(name.upper())\nprint(name.title())\nprint(name.capitalize(), "ABC".lower(), "aBc".swapcase())',
  'str.strip': 'line = "   wood  \\n"\nprint(repr(line.strip()))\nprint(repr("--wood--".strip("-")), repr("  x ".lstrip()))',
  'str.split': 'line = "wood, stone, gold"\nprint(line.split(", "))\nprint("a b   c".split())\nprint("1-2-3".split("-", 1))',
  'str.splitlines': 'text = "erste Zeile\\nzweite Zeile\\n"\nprint(text.splitlines())',
  'str.join': 'res = ["wood", "stone", "gold"]\nprint(", ".join(res))\nprint("-".join(str(i) for i in range(4)))',
  'str.replace': 'print("Holz Holz Holz".replace("Holz", "Stein"))\nprint("a-b-c".replace("-", "", 1))',
  'str.startswith': 'kind = "sword1"\nprint(kind.startswith("sword"), kind.endswith("1"))\nprint("bow2".startswith(("sword", "bow")))',
  'str.find': 's = "wood-stone-wood"\nprint(s.find("wood"), s.rfind("wood"), s.find("gold"))',
  'str.index': 'print("Kronland".index("land"))',
  'str.count': 'print("banana".count("a"), "a,b,c".count(","))',
  'str.isdigit': 'for s in ["42", "4.2", "Holz", "Holz2", " "]:\n    print(repr(s), s.isdigit(), s.isalpha(), s.isalnum(), s.isspace())',
  'str.format': 'print("{} hat {} Holz".format("Nelia", 120))\nprint("{name}: {n:>5}".format(name="Gold", n=300))\nprint("{:.1f} %".format(12.345))',
  'str.center': 'print("[" + "Holz".center(10, "*") + "]")\nprint("[" + "Holz".ljust(8) + "]" + "[" + "12".rjust(5) + "]")',
  'str.zfill': 'print("7".zfill(3), "-42".zfill(5))',
  // ---------- Python: list ----------
  'list.append': 'trees = []\ntrees.append("Eiche")\ntrees.append("Buche")\nprint(trees, len(trees))',
  'list.extend': 'a = [1, 2]\na.extend([3, 4])\na.extend(range(5, 7))\nprint(a)',
  'list.insert': 'queue = ["farm", "residence"]\nqueue.insert(0, "university")\nprint(queue)',
  'list.pop': 'queue = ["farm", "residence", "chapel"]\nlast = queue.pop()\nfirst = queue.pop(0)\nprint(first, last, queue)',
  'list.remove': 'res = ["wood", "gold", "wood"]\nres.remove("wood")\nprint(res)',
  'list.index': 'res = ["wood", "clay", "stone"]\nprint(res.index("stone"))',
  'list.count': 'rolls = [6, 2, 6, 3, 6]\nprint(rolls.count(6))',
  'list.sort': 'amounts = [40, 120, 8]\namounts.sort()\nprint(amounts)\nwords = ["sulfur", "wood", "iron"]\nwords.sort(key=len, reverse=True)\nprint(words)',
  'list.reverse': 'path = [1, 2, 3]\npath.reverse()\nprint(path)',
  'list.copy': 'a = [1, 2, 3]\nb = a.copy()\nb.append(4)\na.clear()\nprint(a, b)',
  'tuple.index': 'pos = (4, 7, 4)\nprint(pos.index(7), pos.count(4))',
  // ---------- Python: dict ----------
  'dict.keys': 'stock = {"wood": 120, "stone": 40}\nprint(list(stock.keys()), list(stock.values()))\nfor res, n in stock.items():\n    print(res, n)',
  'dict.get': 'stock = {"wood": 120}\nprint(stock.get("wood"), stock.get("iron"), stock.get("iron", 0))',
  'dict.pop': 'orders = {"farm": 2, "chapel": 1}\nn = orders.pop("farm")\nprint(n, orders, orders.pop("tower", 0))',
  'dict.setdefault': 'counts = {}\nfor kind in ["tree", "pile", "tree"]:\n    counts.setdefault(kind, 0)\n    counts[kind] += 1\nprint(counts)',
  'dict.update': 'stock = {"wood": 120}\nstock.update({"stone": 40}, gold=300)\nprint(stock)',
  'dict.copy': 'a = {"wood": 1}\nb = a.copy()\nb["wood"] = 99\na.clear()\nprint(a, b)',
};

/** Typical errors per entry: error codes (err.script.…, script.game.…) with the variant after a dot. */
export const ERRORS = {
  wait: ['err.script.type.numberNeeded'],
  notify: ['err.script.argMissing'],
  wait_until: ['err.script.type.callableNeeded', 'err.script.type.waitInSync'],
  'nelia.step': ['script.game.blocked', 'script.game.heroDown'],
  'nelia.turn_to': ['script.game.dirUnknown'],
  'nelia.move_to': ['err.script.type.targetNeeded', 'script.game.placeUnknown', 'script.game.notYours'],
  'nelia.take': ['err.script.game'],
  'nelia.use': ['script.game.abilityNotReady', 'script.game.abilityUnknown', 'script.game.abilityOther', 'script.game.abilityNoTarget',
    'script.game.abilityFar', 'script.game.bribeNoTroop', 'script.game.bribeGold', 'script.game.heroDown'],
  'nelia.ready': ['script.game.abilityUnknown', 'script.game.abilityOther'],
  call_to_arms: ['script.game.notSerf', 'script.game.notYours'],
  'nelia.put': ['err.script.game', 'script.game.itemUnknown'],
  'serf.chop': ['script.game.noTree', 'script.game.interrupted'],
  figures_near: ['script.game.sideUnknown'],
  forecast: ['script.game.noForecast'],
  add_item: ['script.game.itemUnknown'],
  place: ['script.game.placeUnknown'],
  tile: ['err.script.type.numberNeeded'],
  distance: ['err.script.type.targetNeeded', 'script.game.gone'],
  trees_near: ['err.script.type.targetNeeded'],
  piles_near: ['script.game.resUnknown'],
  stock: ['script.game.resUnknown'],
  count: ['script.game.kindUnknown'],
  buildings: ['script.game.buildingUnknown'],
  find_spot: ['script.game.buildingUnknown'],
  can_build: ['script.game.buildingUnknown'],
  build: ['script.game.buildingUnknown', 'err.script.game'],
  buy_serf: ['err.script.game'],
  'serf.work_on': ['err.script.type.entityNeeded', 'script.game.notYours'],
  'troop.attack': ['script.game.notYours', 'script.game.gone'],
  'building.upgrade': ['err.script.game', 'script.game.notYours'],
  'obj.distance_to': ['script.game.gone'],
  'camera.fly_to': ['err.script.type.targetNeeded'],
  every: ['err.script.type.decoratorFunction'],
  objective: ['script.game.objectiveExists'],
  complete: ['script.game.objectiveUnknown'],
  spawn: ['script.game.unitUnknown', 'script.game.playerUnknown'],
  give: ['script.game.resUnknown'],
  set_diplomacy: ['script.game.diplomacyUnknown'],
  give_tech: ['script.game.techUnknown'],
  place_building: ['script.game.buildingUnknown'],
  'nelia.teleport': ['script.game.cannotMove'],
  set_weather: ['script.game.weatherUnknown'],
  'world.height_at': ['script.game.outside'],
  'world.set_height': ['script.game.outside'],
  'world.set_water': ['script.game.outside'],
  add_pile: ['script.game.resUnknown'],
  len: ['err.script.type.noLen'],
  range: ['err.script.type.intNeeded', 'err.script.value.rangeStep'],
  int: ['err.script.value.intLiteral', 'err.script.type.convert'],
  float: ['err.script.value.floatLiteral'],
  min: ['err.script.value.emptySeq', 'err.script.compare'],
  sum: ['err.script.operand'],
  sorted: ['err.script.compare'],
  dict: ['err.script.value.dictPair'],
  round: ['err.script.type.numberNeeded'],
  divmod: ['err.script.zeroDivision'],
  pow: ['err.script.powFraction'],
  chr: ['err.script.value.chrRange', 'err.script.type.ordLength'],
  iter: ['err.script.stopIteration', 'err.script.notIterable'],
  input: ['err.script.notSupported.input'],
  set: ['err.script.notSupported.set'],
  'math.sqrt': ['err.script.mathDomain'],
  'math.isqrt': ['err.script.mathDomain', 'err.script.type.intNeeded'],
  'math.dist': ['err.script.value.distLength'],
  'random.randint': ['err.script.value.emptyRange'],
  'random.choice': ['err.script.index.choiceEmpty'],
  'random.shuffle': ['err.script.type.listNeeded'],
  'str.split': ['err.script.value.emptySeparator'],
  'str.join': ['err.script.type.joinStr'],
  'str.index': ['err.script.value.substringNotFound'],
  'str.format': ['err.script.index.formatIndex', 'err.script.key'],
  'list.pop': ['err.script.index.popEmpty', 'err.script.index.list'],
  'list.remove': ['err.script.value.notInList'],
  'list.index': ['err.script.value.notInList'],
  'list.sort': ['err.script.compare'],
  'dict.pop': ['err.script.key'],
};

/**
 * English wording of the German texts and comments in the examples (plain string examples). Applied for 'en';
 * keeps one example per entry instead of two copies that drift apart.
 */
const EN_TEXT = [
  ['Ich ruhe mich kurz aus.', 'Let me rest for a moment.'], ['Drei Schritte dauerten', 'Three steps took'], ['Holz im Lager:', 'Wood in stock:'],
  ['"Holz: "', '"Wood: "'], ['Holz:', 'Wood:'], ['Vor mir:', 'Ahead of me:'], ['"Schritte"', '"steps"'], ['Aufgehoben:', 'Picked up:'],
  ['Nelia steht bei', 'Nelia stands at'], ['"Noch"', '"Still"'], ['Wasserkacheln in Zeile 20', 'water tiles in row 20'], ['"Kacheln"', '"tiles"'],
  ['Bäume in der Nähe', 'trees nearby'], ['Der nächste steht bei', 'The nearest stands at'], ['"mit"', '"with"'], ['"Holz")', '"wood")'],
  ['Wohnhäuser:', 'Residences:'], ['"Leibeigene:"', '"Serfs:"'], ['"Trupps:"', '"Troops:"'], ['"von"', '"of"'],
  ['Leibeigenen haben nichts zu tun', 'serfs have nothing to do'], ['Soldaten bei', 'soldiers at'], ['"Stufe"', '"level"'],
  ['"fertig" if', '"done" if'], ['"im Bau"', '"under construction"'], ['Burg bei', 'Castle at'], ['Lebenspunkten', 'hit points'],
  ['Platz für einen Bauernhof:', 'Room for a farm:'], ['"Leibeigene")', '"serfs")'], ['Unterwegs, das Programm läuft weiter', 'On the way, the program continues'],
  ['Trupps bewachen das Lager', 'troops guard the camp'], ['Vorsicht vor den Räubern!', 'Beware of the bandits!'], ['eigene Trupps am Tor', 'own troops at the gate'],
  ['Angriff abgewehrt!', 'Attack repelled!'], ['Orrin ist nicht dabei.', 'Orrin is not here.'], ['Bäume gepflanzt', 'trees planted'],
  ['Wasserspiegel:', 'Water level:'], ['Höhe:', 'Height:'], ['# kleiner Hügel um (30, 30)', '# a small hill around (30, 30)'],
  ['# ein Bach quer über die Karte', '# a stream across the map'], ['"Hallo"', '"Hello"'], ['"fertig")', '"done")'],
  ['# input() gibt es nicht – Werte stehen direkt im Programm:', '# there is no input() – values are written into the program:'],
  ['Glück gehabt!', 'Lucky!'], ['nelia von kronland', 'nelia of kronland'], ['erste Zeile\\nzweite Zeile\\n', 'first line\\nsecond line\\n'],
  ['"Holz Holz Holz".replace("Holz", "Stein")', '"wood wood wood".replace("wood", "stone")'], ['"Holz", "Holz2"', '"wood", "wood2"'],
  ['{} hat {} Holz', '{} has {} wood'], ['"Holz".center', '"wood".center'], ['"Holz".ljust', '"wood".ljust'], ['"Eiche"', '"oak"'], ['"Buche"', '"beech"'],
  ['Hallo!', 'Hello!'], ['Angekommen!', 'Arrived!'],
  ['# I.2: im Zickzack den Hang hinauf – eine Schleife mit mehreren Befehlen', '# I.2: up the slope in a zigzag – a loop with several commands'],
  ['# I.5: Schritte bis zum Eis zählen und genauso weit zurückgehen', '# I.5: count the steps up to the ice and walk back just as far'],
  ['Schritte hin und zurück', 'steps there and back'],
  ['# I.M: mit der rechten Hand an den Bäumen durchs Unterholz', '# I.M: through the undergrowth with the right hand on the trees'],
  ['# II.1: eigene Befehle holen die Taler links und rechts vom Weg', '# II.1: own commands fetch the coins left and right of the path'],
  ['# zweimal links: Nelia schaut zurück', '# twice left: Nelia looks back'],
  ['Rechts:', 'Right:'], ['"Hier:"', '"Here:"'], ['Hier liegt:', 'Here lies:'], ['Feinde in der Nähe', 'enemies nearby'], ['Taler in der Nähe', 'thalers nearby'],
  ['Das Wasser ist gefroren und trägt.', 'The water is frozen and carries.'], ['"Wetter:"', '"Weather:"'], ['Ohne Wetterturm keine Vorhersage', 'No forecast without a weather tower'],
  ['"Trupps")', '"troops")'], ['# in dieser Etappe ist das Finden des Fehlers die Aufgabe', '# in this stage finding the mistake is the task'],
  ['# ein junger Baum', '# a young tree'], ['"Taler")', '"thalers")'],
  ['# III.M: ein Dorf nach Bauplan – Gebäude, Holz, Lehm', '# III.M: a village by plan – building, wood, clay'], ['"fertig nach"', '"done after"'], ['"Sekunden"', '"seconds"'],
  ['# Holzfäller: untätige Leibeigene an die nächsten Bäume schicken', '# Lumberjacks: send idle serfs to the nearest trees'],
  ['Leibeigene fällen Bäume', 'serfs are felling trees'], ['Nach 30 Sekunden:', 'After 30 seconds:'], ['Holz mehr', 'more wood'],
  ['# Bestandsaufnahme: Gebäude zählen, Figuren durchlaufen', '# Inventory: count buildings, walk through figures'],
  ['Soldaten, {d} Kacheln von der Burg', 'soldiers, {d} tiles from the castle'], ['Am meisten:', 'Most of all:'],
  ['# Mission: drei Angriffswellen, danach Sieg', '# Mission: three attack waves, then victory'], ['Überstehe drei Angriffe', 'Survive three attacks'],
  ['Welle {waves} kommt!', 'Wave {waves} is coming!'],
  ['# ein Bergkamm zwischen Burg und Lager, mit einem Pass', '# a mountain ridge between castle and camp, with a pass'], ['# ein Bach vom Lager zum Tor', '# a stream from the camp to the gate'],
  ['# der Weg des Spielers wählt die Nachgeschichte (debriefs in scenario.json)', '# the player\'s way picks the epilogue (debriefs in scenario.json)'],
  ['# Weltaufbau: Hügel aus Rauschen, ein Bach, ein Wäldchen und ein Ziel', '# World building: hills from noise, a stream, a grove and a goal'], ['Genug Holz!', 'Enough wood!'],
];

/** Example of an entry in a language (or null). */
export function refExample(name, lang = 'de') {
  const ex = EXAMPLES[name] ?? WORKED[name]?.code;
  if (ex === undefined || ex === null) return null;
  if (typeof ex !== 'string') return ex[lang] ?? ex.de;
  if (lang !== 'en') return ex;
  return EN_TEXT.reduce((s, [de, en]) => s.split(de).join(en), ex);
}

/** Anchor of an entry on the reference page: the name itself (nelia.step, len, str.split …). */
export const refAnchor = (name) => BASICS_ANCHOR[name] ?? name;

/** Address of the reference page (optionally at an entry), relative to the current page. */
export const refUrl = (name) => siteUrl('scripting/') + (name ? `#${encodeURIComponent(refAnchor(name))}` : '');

/**
 * Longer worked examples for the reference (chapter "examples"). course + stage: solves this stage of a course
 * mission (played stage by stage in both languages in tests/levels/course.test.js); level: runs as player program or
 * mission script in the test scenario (tests/site/scripting.test.js).
 */
export const WORKED = {
  zigzag: { course: 'r1-2', stage: 'slope', code: '# I.2: im Zickzack den Hang hinauf – eine Schleife mit mehreren Befehlen\nfor i in range(5):\n    nelia.step()\n    nelia.turn_left()\n    nelia.step()\n    nelia.turn_right()\n' },
  brook: { course: 'r1-5', stage: 'brook', code: '# I.5: Schritte bis zum Eis zählen und genauso weit zurückgehen\nsteps = 0\nwhile nelia.front() != "ice":\n    nelia.step()\n    steps = steps + 1\nnelia.turn_left()\nnelia.turn_left()\nfor i in range(steps):\n    nelia.step()\nprint(steps, "Schritte hin und zurück")\n' },
  thicket: { course: 'r1-m', stage: 'thicket', code: '# I.M: mit der rechten Hand an den Bäumen durchs Unterholz\nwhile not nelia.is_at(place("exit")):\n    if nelia.right() == "free":\n        nelia.turn_right()\n        nelia.step()\n    elif nelia.can_step():\n        nelia.step()\n    else:\n        nelia.turn_left()\n' },
  fetch: { course: 'r2-1', stage: 'coins', code: '# II.1: eigene Befehle holen die Taler links und rechts vom Weg\ndef turn_around():\n    nelia.turn_left()\n    nelia.turn_left()  # zweimal links: Nelia schaut zurück\n\ndef fetch_left():\n    nelia.turn_left()\n    nelia.step()\n    nelia.take()\n    turn_around()\n    nelia.step()\n    nelia.turn_left()\n\ndef fetch_right():\n    nelia.turn_right()\n    nelia.step()\n    nelia.take()\n    turn_around()\n    nelia.step()\n    nelia.turn_right()\n\nwhile nelia.can_step():\n    nelia.step()\n    if nelia.left() == "coin":\n        fetch_left()\n    if nelia.right() == "coin":\n        fetch_right()\n' },
  village: { course: 'r3-m', stage: 'farms', code: '# III.M: ein Dorf nach Bauplan – Gebäude, Holz, Lehm\nplan = [["villageCenter", 300, 300], ["residence", 150, 100], ["residence", 150, 100], ["farm", 200, 150], ["farm", 200, 150]]\nhelpers = serfs()\npiles = piles_near(hq(), 12, "wood") + piles_near(hq(), 12, "clay")\n\ndef gather():\n    for i in range(len(helpers)):\n        helpers[i].work_on(piles[i % len(piles)])\n\ndef build_on(kind):\n    spot = find_spot(kind, hq())\n    return build(kind, spot[0], spot[1])\n\nfor step in plan:\n    gather()\n    wait_until(lambda: stock("wood") >= step[1] and stock("clay") >= step[2])\n    site = build_on(step[0])\n    for s in helpers:\n        s.work_on(site)\n    wait_until(lambda: site.done)\n    print(step[0], "fertig nach", round(time()), "Sekunden")\n' },
  lumber: {
    level: 'player',
    code: '# Holzfäller: untätige Leibeigene an die nächsten Bäume schicken\ndef lumber(n):\n    trees = trees_near(hq(), radius=15)\n    idle = serfs(idle=True)\n    pairs = list(zip(idle[:n], trees))\n    for serf, tree in pairs:\n        serf.work_on(tree)\n    return len(pairs)\n\nstart = stock("wood")\nprint(lumber(4), "Leibeigene fällen Bäume")\nwait(30)\nprint("Nach 30 Sekunden:", stock("wood") - start, "Holz mehr")\n',
  },
  report: {
    level: 'player',
    code: '# Bestandsaufnahme: Gebäude zählen, Figuren durchlaufen\ncounts = {}\nfor b in buildings():\n    counts[b.type] = counts.get(b.type, 0) + 1\nfor kind in sorted(counts):\n    print(kind.ljust(14), counts[kind])\n\nfor t in troops():\n    d = round(t.distance_to(hq()), 1)\n    print(f"{t.type}: {t.soldiers} Soldaten, {d} Kacheln von der Burg")\n\nresources = ["wood", "clay", "stone", "iron", "sulfur", "gold"]\nrichest = max(resources, key=stock)\nprint("Am meisten:", richest, stock(richest))\n',
  },
  waves: {
    level: 'mission',
    code: '# Mission: drei Angriffswellen, danach Sieg\nobjective("hold", de="Überstehe drei Angriffe", en="Survive three attacks")\nwaves = 0\n\n@every(60)\ndef raid():\n    global waves\n    if waves >= 3:\n        return\n    waves += 1\n    message(f"Welle {waves} kommt!")\n    attackers = spawn(BANDITS, "sword1", place("gate"), count=waves)\n    attack(attackers, hq())\n    wait_until(lambda: alive(attackers) == 0)\n    if waves == 3:\n        complete("hold")\n\n@on_objective("hold", status="done")\ndef won(id, status):\n    victory()\n\n@on_destroyed("headquarters", HUMAN)\ndef lost(kind, owner):\n    defeat("hq")\n',
  },
  world: {
    level: 'mission',
    code: '# Weltaufbau: Hügel aus Rauschen, ein Bach, ein Wäldchen und ein Ziel\nfor x in range(world.width):\n    for y in range(world.height):\n        n = world.noise(x, y, cell=12)\n        world.set_height(x, y, n // 2)\n\nfor y in range(world.height):\n    world.set_water(40, y)\n\nplant_trees(toward(hq(), map_center(), 12), 20, radius=4)\nspot = find_open(map_center(), min_r=6, max_r=20)\nmake_place("goal", spot.x, spot.y, 2)\nreveal(place("goal"))\n',
  },
};
